# copied from https://github.com/eu-digital-identity-wallet/eudi-docs-site/blob/main/mkdocs.yml
site_name: European Digital Identity
site_author: European Commission - DG CNECT

repo_url: https://github.com/eu-digital-identity-wallet/eudi-doc-functional-conformance-assessment
repo_name: eu-digital-identity-wallet/eudi-doc-functional-conformance-assessment
site_url: https://conformance.eudi.dev

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.indexes
# specific
    - toc.integrate
    - toc.follow
# specific

  icon:
    repo: fontawesome/brands/github

  logo: media/images/logo_eudi_white.svg
  favicon: media/images/favicon.ico

extra_css:
  - media/css/extra.css

markdown_extensions:
  - footnotes
  - sane_lists
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version:
    provider: mike
    alias: true

plugins:
  - mike
  - tags
  - privacy
  - social

nav:
  - Functional Conformance Assessment Framework (FCAF):
      - Home: index.md
      - Introduction: introduction.md
      - Methodology: fcaf/index.md
      - Test Suites by SUTs:
          - Overview: fcaf/suts/index.md
          - Wallet Solution (SUT):
              - Overview: fcaf/suts/wallet_solution/index.md
              - Test Classes:
                  - Relying Party (ws_rp): fcaf/suts/wallet_solution/relying_party/ws_rp.md
                  - Attestation Provider (ws_ap): fcaf/suts/wallet_solution/attestation_provider/ws_ap.md
                  - PID Provider (ws_pp): fcaf/suts/wallet_solution/pid_provider/ws_pp.md
                  - Infrastructure (ws_inf): fcaf/suts/wallet_solution/infrastructure/ws_inf.md
                  - UI (ws_ui): fcaf/suts/wallet_solution/ui/ws_ui.md
      - Templates:
          - Overview: fcaf/templates/index.md
          - Test spec template: fcaf/templates/test-spec-template.md

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js