name: Publish draft docs

on:
  push:
    branches:
      - submitted

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    uses: eu-digital-identity-wallet/eudi-doc-functional-conformance-assessment/.github/workflows/pages.yml@site
    with:
      content_ref: submitted
